<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>9</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\..\CodeBoost\CodeBoost\**\*.cs" Link="CodeBoost\%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.9.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Common\" />
      <Folder Include="SourceGenerators\" />
    </ItemGroup>

</Project>

