<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.11.0-3.final" />
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0-3.final" />
      <PackageReference Include="Roslyn.Diagnostics.Analyzers" Version="3.11.0-beta1.24318.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Compile Include="..\Roslyn\Constants\NativeConstants.cs">
        <Link>Roslyn\Constants\NativeConstants.cs</Link>
      </Compile>
      <Compile Include="..\Roslyn\Extensions\AttributeDataExtensions.cs">
        <Link>Roslyn\Extensions\AttributeDataExtensions.cs</Link>
      </Compile>
      <Compile Include="..\Roslyn\Extensions\EnumExtensions.cs">
        <Link>Roslyn\Extensions\EnumExtensions.cs</Link>
      </Compile>
      <Compile Include="..\Roslyn\Extensions\IAssemblySymbolExtensions.cs">
        <Link>Roslyn\Extensions\IAssemblySymbolExtensions.cs</Link>
      </Compile>
      <Compile Include="..\Roslyn\Extensions\INamedTypeSymbolExtensions.cs">
        <Link>Roslyn\Extensions\INamedTypeSymbolExtensions.cs</Link>
      </Compile>
      <Compile Include="..\Roslyn\Extensions\IntExtensions.cs">
        <Link>Roslyn\Extensions\IntExtensions.cs</Link>
      </Compile>
      <Compile Include="..\Roslyn\Extensions\ISymbolExtensions.cs">
        <Link>Roslyn\Extensions\ISymbolExtensions.cs</Link>
      </Compile>
      <Compile Include="..\Roslyn\Extensions\ITypeSymbolExtensions.cs">
        <Link>Roslyn\Extensions\ITypeSymbolExtensions.cs</Link>
      </Compile>
      <Compile Include="..\Roslyn\Extensions\SemanticModelExtensions.cs">
        <Link>Roslyn\Extensions\SemanticModelExtensions.cs</Link>
      </Compile>
      <Compile Include="..\Roslyn\Extensions\StringBuilderExtensions.cs">
        <Link>Roslyn\Extensions\StringBuilderExtensions.cs</Link>
      </Compile>
      <Compile Include="..\Roslyn\Extensions\StringExtensions.cs">
        <Link>Roslyn\Extensions\StringExtensions.cs</Link>
      </Compile>
      <Compile Include="..\Roslyn\Extensions\SyntaxNodeExtensions.cs">
        <Link>Roslyn\Extensions\SyntaxNodeExtensions.cs</Link>
      </Compile>
    </ItemGroup>

</Project>
