<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <RootNamespace>CodeAnalysis.Common</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\..\CodeBoost\CodeBoost\**\*.cs" Link="CodeBoost\%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>

</Project>

