<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <RootNamespace>FishNet.SourceAnaylzer</RootNamespace>
    </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.9.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />
		<PackageReference Include="Roslyn.Diagnostics.Analyzers" Version="3.3.4">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\FirstGearGames.Roslyn\**\*.cs">
			<Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
		</Compile>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Extensions\" />
	</ItemGroup>


</Project>
