<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<AnalysisLevel>latest</AnalysisLevel>
		<Nullable>enable</Nullable>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.9.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Update="..\Roslyn" />
	  <Folder Include="..\Roslyn.Shared\bin\Release\netstandard2.0\">
	    <Link>Roslyn.Shared\bin\Release\netstandard2.0</Link>
	  </Folder>
	</ItemGroup>
	<ItemGroup>
	  <Content Include="..\Roslyn.Shared\obj\project.assets.json">
	    <Link>Roslyn.Shared\obj\project.assets.json</Link>
	  </Content>
	  <Content Include="..\Roslyn.Shared\obj\project.nuget.cache">
	    <Link>Roslyn.Shared\obj\project.nuget.cache</Link>
	  </Content>
	  <Content Include="..\Roslyn.Shared\obj\project.packagespec.json">
	    <Link>Roslyn.Shared\obj\project.packagespec.json</Link>
	  </Content>
	  <Content Include="..\Roslyn.Shared\obj\Release\netstandard2.0\Roslyn.Shared.AssemblyInfoInputs.cache">
	    <Link>Roslyn.Shared\obj\Release\netstandard2.0\Roslyn.Shared.AssemblyInfoInputs.cache</Link>
	  </Content>
	  <Content Include="..\Roslyn.Shared\obj\Release\netstandard2.0\Roslyn.Shared.assets.cache">
	    <Link>Roslyn.Shared\obj\Release\netstandard2.0\Roslyn.Shared.assets.cache</Link>
	  </Content>
	  <Content Include="..\Roslyn.Shared\obj\Release\netstandard2.0\Roslyn.Shared.csproj.AssemblyReference.cache">
	    <Link>Roslyn.Shared\obj\Release\netstandard2.0\Roslyn.Shared.csproj.AssemblyReference.cache</Link>
	  </Content>
	  <Content Include="..\Roslyn.Shared\obj\Release\netstandard2.0\Roslyn.Shared.GeneratedMSBuildEditorConfig.editorconfig">
	    <Link>Roslyn.Shared\obj\Release\netstandard2.0\Roslyn.Shared.GeneratedMSBuildEditorConfig.editorconfig</Link>
	  </Content>
	  <Content Include="..\Roslyn.Shared\obj\rider.project.model.nuget.info">
	    <Link>Roslyn.Shared\obj\rider.project.model.nuget.info</Link>
	  </Content>
	  <Content Include="..\Roslyn.Shared\obj\rider.project.restore.info">
	    <Link>Roslyn.Shared\obj\rider.project.restore.info</Link>
	  </Content>
	  <Content Include="..\Roslyn.Shared\obj\Roslyn.Shared.csproj.nuget.dgspec.json">
	    <Link>Roslyn.Shared\obj\Roslyn.Shared.csproj.nuget.dgspec.json</Link>
	  </Content>
	  <Content Include="..\Roslyn.Shared\obj\Roslyn.Shared.csproj.nuget.g.props">
	    <Link>Roslyn.Shared\obj\Roslyn.Shared.csproj.nuget.g.props</Link>
	  </Content>
	  <Content Include="..\Roslyn.Shared\obj\Roslyn.Shared.csproj.nuget.g.targets">
	    <Link>Roslyn.Shared\obj\Roslyn.Shared.csproj.nuget.g.targets</Link>
	  </Content>
	  <Content Include="..\Roslyn.Shared\Roslyn.Shared.csproj">
	    <Link>Roslyn.Shared\Roslyn.Shared.csproj</Link>
	  </Content>
	</ItemGroup>
	<ItemGroup>
	  <Compile Include="..\Roslyn.Shared\CodeBuilding\CodeBuilder.cs">
	    <Link>Roslyn.Shared\CodeBuilding\CodeBuilder.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\Constants\NativeConstants.cs">
	    <Link>Roslyn.Shared\Constants\NativeConstants.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\Extensions\AttributeDataExtensions.cs">
	    <Link>Roslyn.Shared\Extensions\AttributeDataExtensions.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\Extensions\EnumExtensions.cs">
	    <Link>Roslyn.Shared\Extensions\EnumExtensions.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\Extensions\IAssemblySymbolExtensions.cs">
	    <Link>Roslyn.Shared\Extensions\IAssemblySymbolExtensions.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\Extensions\INamedTypeSymbolExtensions.cs">
	    <Link>Roslyn.Shared\Extensions\INamedTypeSymbolExtensions.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\Extensions\IntExtensions.cs">
	    <Link>Roslyn.Shared\Extensions\IntExtensions.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\Extensions\ISymbolExtensions.cs">
	    <Link>Roslyn.Shared\Extensions\ISymbolExtensions.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\Extensions\ITypeSymbolExtensions.cs">
	    <Link>Roslyn.Shared\Extensions\ITypeSymbolExtensions.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\Extensions\SemanticModelExtensions.cs">
	    <Link>Roslyn.Shared\Extensions\SemanticModelExtensions.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\Extensions\StringBuilderExtensions.cs">
	    <Link>Roslyn.Shared\Extensions\StringBuilderExtensions.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\Extensions\StringExtensions.cs">
	    <Link>Roslyn.Shared\Extensions\StringExtensions.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\Extensions\SyntaxNodeExtensions.cs">
	    <Link>Roslyn.Shared\Extensions\SyntaxNodeExtensions.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\FishNet\Constants\FishNetConstants.cs">
	    <Link>Roslyn.Shared\FishNet\Constants\FishNetConstants.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\FishNet\Constants\UnityConstants.cs">
	    <Link>Roslyn.Shared\FishNet\Constants\UnityConstants.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\FishNet\Helpers\DebugHelper.cs">
	    <Link>Roslyn.Shared\FishNet\Helpers\DebugHelper.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\FishNet\Helpers\RpcHelpers.cs">
	    <Link>Roslyn.Shared\FishNet\Helpers\RpcHelpers.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\FishNet\Serializing\SerializableType.cs">
	    <Link>Roslyn.Shared\FishNet\Serializing\SerializableType.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\FishNet\Serializing\SerializerReceiver.cs">
	    <Link>Roslyn.Shared\FishNet\Serializing\SerializerReceiver.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\obj\Release\netstandard2.0\.NETStandard,Version=v2.0.AssemblyAttributes.cs">
	    <Link>Roslyn.Shared\obj\Release\netstandard2.0\.NETStandard,Version=v2.0.AssemblyAttributes.cs</Link>
	  </Compile>
	  <Compile Include="..\Roslyn.Shared\obj\Release\netstandard2.0\Roslyn.Shared.AssemblyInfo.cs">
	    <Link>Roslyn.Shared\obj\Release\netstandard2.0\Roslyn.Shared.AssemblyInfo.cs</Link>
	  </Compile>
	</ItemGroup>
</Project>
