<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>9</LangVersion>
		<AnalysisLevel>latest</AnalysisLevel>
		<Nullable>disable</Nullable>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<AssemblyName>FirstGearGames.LV.CodeAnalysis.SourceGenerators</AssemblyName>
		<RootNamespace>FirstGearGames.LV.CodeAnalysis.SourceGenerators</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.9.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />
	</ItemGroup>

	<Import Project="..\FirstGearGames.CodeAnalysis.Common\FirstGearGames.CodeAnalysis.Common.projitems" Label="Shared" />
	
	<PropertyGroup>
		<ImplicitUsings>disable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
	</PropertyGroup>

	<PropertyGroup>
		<NoWarn>$(NoWarn);CS8618</NoWarn>
		<NoWarn>$(NoWarn);CS8625</NoWarn>
		<NoWarn>$(NoWarn);CS0067</NoWarn>
		<NoWarn>$(NoWarn);RS0016</NoWarn>
	</PropertyGroup>
	
</Project>
